created bash function `qpdfmerge`
- added function code to `bashrc`

diff --git a/etc/bash/bashrc b/etc/bash/bashrc
--- a/etc/bash/bashrc
+++ b/etc/bash/bashrc
@@ -54,7 +54,18 @@ export GTK2_RC_FILES="~/.gtkrc-2.0"
 #
 # user specific functions
 #
-# TODO
+
+__qpdf=`command -v qpdf`
+if [ -n "${__qpdf}" ]; then
+    function qpdfmerge {
+        local OUTPUT=$1 && shift
+        if [ -e "${OUTPUT}" ]; then
+            echo "Error: output file: \"${OUTPUT}\" already exists" 1>&2
+            return -1
+        fi
+        "${__qpdf}" --min-version=1.7 --linearize --normalize-content=y --object-streams=generate --stream-data=compress --empty --pages "$@" -- "${OUTPUT}"
+    }
+fi
 
 #
 # user specific aliases
